---
title: "Research"
---

# Journal articles

How to increase citizen coproduction : Replication and extension of existing research. / Andersen, Simon Calmar; Nielsen, Helena Skyt; Thomsen, Mette Kjærgaard.
International Public Management Journal, Bind 23, Nr. 5, 09.2020, s. 696-712.


Development and validation of the Danish Big Five Inventory-2: Domain- and facet-level structure, construct validity, and reliability. / Vedel, Anna; Wellnitz, Kaare Bro; Ludeke, Steven; Soto, Christopher J.; John, Oliver P.; Andersen, Simon Calmar.
European Journal of Psychological Assessment, 24.03.2020.




The Effect of Teacher's Aides in the Classroom : Evidence from a Randomized Trial. / Andersen, Simon Calmar; Beuchert-Pedersen, Louise Voldby; Nielsen, Helena Skyt; Thomsen, Mette Kjærgaard.
Journal of the European Economic Association, Bind 18, Nr. 1, 02.2020, s. 469-505.




A Cluster-Randomized Trial Measuring the Effects of a Digital Learning Tool Supporting Decoding and Reading for Meaning in Grade 2. / Gissel, Stig Toke; Andersen, Simon Calmar.
Journal of Computer Assisted Learning, 2020.




A Stable Relationship Between Personality and Academic Performance from Childhood through Adolescence : An original study and replication in hundred-thousand-person samples. / Andersen, Simon Calmar; Gensowski, Miriam; Ludeke, Steven; John, Oliver P.
Journal of Personality, Bind 88, Nr. 5, 2020, s. 925-939.




Can Reminders and Incentives Improve Implementation Within Government? Evidence from a Field Experiment. / Andersen, Simon Calmar; Hvidman, Ulrik.
Journal of Public Administration Research and Theory, 2020.




Does parental education influence child educational outcomes? A developmental analysis in a full-population sample and adoptee design. / Ludeke, Steven; Gensowski, Miriam; Junge, Sarah Yde; Kirkpatrick, Robert M.; John, Oliver P.; Andersen, Simon Calmar.
Journal of Personality and Social Psychology, 2020.




Learning from Performance Information. / Andersen, Simon Calmar; Nielsen, Helena Skyt.
Journal of Public Administration Research and Theory, Bind 30, Nr. 3, 2020, s. 415-431.




Parent Involvement, Socioeconomic Status and Reading Performance. / Andersen, Simon Calmar; Gregersen, Maria Koch; Nielsen, Helena Skyt; Thomsen, Mette Kjærgaard.
Scandinavian Journal of Educational Research, 2020.


## 2019


Reducing Minority Discrimination at the Front Line - Combined Survey and Field Experimental Evidence. / Andersen, Simon Calmar; Guul, Thorbjørn Sejr.
Journal of Public Administration Research and Theory, Bind 29, Nr. 3, 07.2019, s. 429-444.




The Unnoticed Influence of Peers on Educational Preferences. / Andersen, Simon Calmar; Hjortskov, Morten.
Behavioral Public Policy, 2019, s. 1-24.


## 2018


Randomised controlled trials in Scandinavian educational research. / Pontoppidan, Maiken; Keilow, Maria; Dietrichson, Jens; Solheim, Oddny Judith ; Opheim, Vibeke; Gustafson, Stefan; Andersen, Simon Calmar.
Educational Research, Bind 60, Nr. 3, 03.07.2018, s. 311-335.




Encouraging Political Voices of Underrepresented Citizens through Coproduction: Evidence from a Randomized Field Trial. / Hjortskov, Morten; Andersen, Simon Calmar; Jakobsen, Morten.
American Journal of Political Science, Bind 62, Nr. 3, 2018, s. 597-609.




How Do Socially Distinctive Newcomers Fare? Evidence from a Field Experiment. / Andersen, Simon Calmar; Moynihan, Donald P.
Public Administration Review, Bind 78, Nr. 6, 2018, s. 874-882.




How Should We Estimate the Performance Effect of Management? Comparing Impacts of Public Managers' and Frontline Employees' Perceptions of Management. / Favero, Nathan; Andersen, Simon Calmar; Meier, Kenneth J.; O'Toole, Laurence J.; Winter, Søren.
International Public Management Journal, Bind 21, Nr. 1, 2018, s. 105-130.




How reading and writing support each other across a school year in primary school children. / Andersen, Simon Calmar; Christensen, Mette Vedsgaard; Nielsen, Helena Skyt; Thomsen, Mette Kjærgaard; Østerbye, Torkil; Rowe, Meredith L.
Contemporary Educational Psychology, Bind 55, 2018, s. 129-138.




Political Pressure, Conformity Pressure, and Performance Information as Drivers of Public Sector Innovation Adoption. / Andersen, Simon Calmar; Jakobsen, Mads Leth.
International Public Management Journal, Bind 21, Nr. 2, 2018, s. 213-242.


## 2017


Influence of motor skills training on children’s development evaluated in the Motor skills in PreSchool (MiPS) study-DK: study protocol for a randomized controlled trial, nested in a cohort study. / Hestbaek, Lise; Andersen, Sara Thurøe; Skovgaard, Thomas; Olesen, Line Groenholt ; Elmose, Mette ; Bleses, Dorthe; Andersen, Simon Calmar; Lauridsen, Henrik Hein.
Trials, Bind 18, Nr. 400, 09.08.2017.




From Passive to Active Representation: Experimental Evidence on the Role of Normative Values in Shaping White and Minority Bureaucrats' Policy Attitudes. / Andersen, Simon Calmar.
Journal of Public Administration Research and Theory, Bind 27, Nr. 3, 2017, s. 400–414.




Policy Positions of Bureaucrats at the Front Lines: Are They Susceptible to Strategic Communication? / Andersen, Simon Calmar; Jakobsen, Morten.
Public Administration Review, Bind 77, Nr. 1, 2017, s. 57-66.




Student-Centered Instruction and Academic Achievement: Linking Mechanisms of Educational Inequality to Schools’ Instructional Strategy. / Andersen, Ida Gran; Andersen, Simon Calmar.
British Journal of Sociology of Education, Bind 38, Nr. 4, 2017, s. 533-550.


## 2016


Bureaucratic Investments in Expertise: Evidence From a Randomized Controlled Field Trial. / Andersen, Simon Calmar; Moynihan, Donald P.
The Journal of Politics, Bind 78, Nr. 4, 2016, s. 1032-1044.




Cognitive Biases in Performance Evaluations. / Andersen, Simon Calmar; Larsen, Morten Hjortskov.
Journal of Public Administration Research and Theory, Bind 26, Nr. 4, 2016, s. 647-662.




Forskning i ledelseseffekter på borgernes udbytte af de offentlige ydelser: styrker, svagheder og fremtidige perspektiver. / Andersen, Lotte Bøgh; Andersen, Simon Calmar; Pallesen, Thomas.
Politica - Tidsskrift for politisk videnskab, Bind 48, Nr. 2, 2016, s. 113-134.




How Leaders Respond to Diversity: The Moderating Role of Organizational Culture on Performance Information Use. / Andersen, Simon Calmar; Moynihan, Donald P.
Journal of Public Administration Research and Theory, Bind 26, Nr. 3, 2016, s. 448-460.




Increasing instruction time in school does increase learning. / Andersen, Simon Calmar; Humlum, Maria; Nandrup, Anne Brink.
Proceedings of the National Academy of Sciences of the United States of America, Bind 113, Nr. 27, 2016, s. 7481-7484.




Perceptions of Public and Private Performance: Evidence from a Survey Experiment. / Hvidman, Ulrik; Andersen, Simon Calmar.
Public Administration Review, Bind 76, Nr. 1, 2016, s. 111-120.




Reading intervention with a growth mindset approach improves children’s skills. / Andersen, Simon Calmar; Nielsen, Helena Skyt.
Proceedings of the National Academy of Sciences of the United States of America, Bind 113, Nr. 43, 2016, s. 12111-12113.


## 2015


Brugernes reaktion når det offentlige øger serviceniveauet. Resultater fra et lodtrækningsforsøg på skoleområdet. / Andersen, Simon Calmar; Nielsen, Helena Skyt; Thomsen, Mette Kjærgaard.
Politica - Tidsskrift for politisk videnskab, Bind 47, Nr. 2, 2015, s. 125-143.




Taking Managerial Context Seriously : Public Management and Performance in U.S. and Denmark Schools. / Meier, Kenneth J.; Andersen, Simon Calmar; O'Toole, Laurence J.; Favero, Nathan; Winter, Søren C.
International Public Management Journal, Bind 18, Nr. 1, 2015, s. 130-150.




The Validity of Subjective Performance Measures : School Principals in Texas and Denmark. / Meier, Kenneth J.; Winter, Søren C.; O'Toole, Laurence J.; Favero, Nathan; Andersen, Simon Calmar.
Public Administration, Bind 93, Nr. 4, 2015, s. 1084-1101.


## 2014


Deliberative Democratic Governance. / Andersen, Simon Calmar; Loftager, Jørn.
Administrative Theory & Praxis, Bind 36, Nr. 4, 2014, s. 510-529.




Impact of Performance Management in Public and Private Organizations. / Hvidman, Ulrik; Andersen, Simon Calmar.
Journal of Public Administration Research and Theory, Bind 24, Nr. 1, 2014, s. 35-58.


## 2013


Coproduction and Equity in Public Service Delivery. / Jakobsen, Morten; Andersen, Simon Calmar.
Public Administration Review, Bind 73, Nr. 5, 2013, s. 704-713.




Intensifying Social Exchange Relationships in Public Organizations: Evidence from a Randomized Field Experiment. / Jakobsen, Morten; Andersen, Simon Calmar.
Journal of Policy Analysis and Management, Bind 32, Nr. 1, 2013, s. 60-82.


## 2011


Policy Implications of Limiting Immigrant Concentration in Danish Public Schools. / Andersen, Simon Calmar; Thomsen, Mette Kjærgaard.
Scandinavian Political Studies, Bind 34, Nr. 1, 2011, s. 27-52.


## 2010


Policy Stability and Organizational Performance: Is There a Relationship? / Andersen, Simon Calmar; Mortensen, Peter Bjerre.
Journal of Public Administration Research and Theory, Bind 20, Nr. 1, 2010, s. 1-22.


## 2008


Private schools and the parents that choose them. / Andersen, Simon Calmar.
Scandinavian Political Studies, Bind 31, Nr. 1, 2008, s. 44-68.




The Impact of Public Management Reforms on Student Performance in Danish Schools. / Andersen, Simon Calmar.
Public Administration, Bind 86, Nr. 2, 2008, s. 541-558.


## 2007


Multilevel-modeller: en introduktion og et eksempel. / Andersen, Simon Calmar.
Politica, Nr. 3, 2007, s. 294-316.

Publikation: Bidrag til tidsskrift/Konferencebidrag i tidsskrift /Bidrag til avis › Tidsskriftartikel › Forskning


The Unintended Effects of Private School Competition. / Andersen, Simon Calmar; Serritzlew, Søren.
Journal of Public Administration Research and Theory, Bind 17, Nr. 2, 2007, s. 335-356.


## 2006


Når New Public Management møder uddannelsessystemet. / Andersen, Simon Calmar.
Nordisk Administrativt Tidsskrift, Bind 2, 2006, s. 121-136.




Styring gennem autonomi? Et forskningsprojekt om politisk styring af de danske skoler. / Andersen, Simon Calmar.
Politica, Bind 38, Nr. 4, 2006, s. 426-445.


## 2005


How to Improve the Outcome of State Welfare Services : Governance in a Systems-Theoretical Perspective. / Andersen, Simon Calmar.
Public Administration, Bind 83, Nr. 4, 2005, s. 891-907.




Smid ikke metoderne ud med badevandet. Epistemologisk konstruktivisme og dens metodiske konsekvenser. / Andersen, Simon Calmar.
Dansk Sociologi, Bind 3, 2005, s. 45-60.


## 2004


Hvorfor bliver man ved med at evaluere folkeskolen? / Andersen, S.C.
Politica, Bind 36, Nr. 4, 2004, s. 452-468.

## 2002


Anmeldelse af Erik Oddvar Eriksen, Demokratiets sorte hull - om spenningen mellom fag og politikk i velferdsstaten, Oslo: Abstrakt forlag, 2001, 283 s. / Andersen, S.C.
Politica, Bind 34, Nr. 3, 2002, s. 344-346.


